name: Build & test

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build.yml"
      - ".github/workflows/codecov.yml"
      - ".github/scripts/coverage.sh"
      - "src/**"
      - "scripts/**"
      - "test/**"

jobs:
  run-codecov:
    uses: ./.github/workflows/codecov.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
