name: Codecov check

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

concurrency:
  group: "codecov"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'test skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile and run tests
        uses: addnab/docker-run-action@v3
        with:
          image: jihoonjang2/automata:hw2
          shell: bash
          options: -v ${{ github.workspace }}:/work
          run: |
            cd /work
            apt install lcov parallel python3-pip -y
            python3 -m pip install -r test-requirements.txt
            scripts/compile.sh -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
            .github/scripts/coverage.sh build

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.info
          fail_ci_if_error: true
          verbose: true
